"""add user ownership to items

Revision ID: 7af5d82b2c8d
Revises: 91ee92ec441a
Create Date: 2026-08-11 18:23:12.116404

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7af5d82b2c8d"
down_revision: Union[str, Sequence[str], None] = "91ee92ec441a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "items", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "items", type_="foreignkey")
    op.drop_column("items", "user_id")
    # ### end Alembic commands ###
