"""add brand to items

Revision ID: adcd04bfdb87
Revises: 7eea3c7edf57
Create Date: 2026-07-29 19:57:36.039068

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "adcd04bfdb87"
down_revision: Union[str, Sequence[str], None] = "7eea3c7edf57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("brand", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "brand")
    # ### end Alembic commands ###
