"""add item details

Revision ID: d96f5a81cbe8
Revises: 7af5d82b2c8d
Create Date: 2026-08-14 18:37:00.564561

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d96f5a81cbe8"
down_revision: Union[str, Sequence[str], None] = "7af5d82b2c8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items", sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True)
    )
    op.add_column("items", sa.Column("purchase_date", sa.Date(), nullable=True))
    op.add_column("items", sa.Column("condition", sa.String(length=50), nullable=True))
    op.add_column("items", sa.Column("notes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "notes")
    op.drop_column("items", "condition")
    op.drop_column("items", "purchase_date")
    op.drop_column("items", "price")
    # ### end Alembic commands ###
